# hpa.yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: testweb-hpa
  labels:
    app: testweb-hpa
spec:
  minReplicas: 1
  maxReplicas: 10

  #Scale할 조건
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 5
    type: Resource

  #Scale할 ReplicaSet 설정
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: testweb-deployment